### PR TITLE
track.applyConstraints and canvas.captureStream in FF43 (Nightly)

### PR DESCRIPTION
**Pull request by jan-ivar**

### CODE REVIEW

**Comment by xdumaine** [comment]
Changes like this are what cause a lot of confusion, IMO. @jan-ivar you act like changes are "done" and claim "firefox supports x" even if the feature is 2 or 3 releases out from firefox stable. This PR is for a feature 3 releases out from stable, and for another example, you claimed the same on that SO question about device selection, that "firefox has supported it for months" even though the version that supports it is still 2 releases out from stable (42).

**Comment by xdumaine** [comment]
... and I just realized you changed it on nightlies, not FF, but my point stands about the other feature. Sorry for coming off like an ass, it's just very confusing as a consumer of these things to see comments about it's support, but not clarifying that it's in a beta or alpha channel.

**Comment by jan-ivar** [comment]
@xdumaine Are you referring to [this](http://stackoverflow.com/q/32522293/918910)? There, I confused deviced selection (42) with device enumeration (39), my mistake, I meant to address Benjamin's comment and outdated link on the latter. But I corrected it a day later.

Hopefully nothing is unclear here in this issue (everything is in FF43 aka Nightly).

**Comment by fippo** [comment]
I wonder if we should use title to indicate the nightly/canary version for things like this. That would also help in spotting things which have trickled down to the stable version but haven't been updated yet.

**Comment by jan-ivar** [comment]
wfm

**Comment by jan-ivar** [comment]
actually, wont that be confusing? what "nightly" means changes over time, while 43 doesn't (like UTC vs EDT)

**Comment by jan-ivar** [comment]
wfm :)

**Pull request merged**
