### PR TITLE
add vp9 support

### PR DESCRIPTION
**Pull request by fippo**
showing the highly experimental VP9 support

### CODE REVIEW

**Comment by stefanalund** [comment]
I would argue that codecs that are not part of the WebRTC standards spec, such as VP9 and H.265, should not be on this list.

**Comment by fippo** [comment]
Well, you probably shouldn't get a "red == bad" thing for this. But I want to add things like G.722 as well, which isn't MTI either

**Comment by stefanalund** [comment]
Still, I think it's important to distinguish between a standard and its implementations. There is already too much confusion around that in the WebRTC space.

**Comment by fippo** [comment]
reverted -- I think this needs more discussion -- tomorrow most likely

**Comment by bear** [comment]
@fippo I'll leave the branch around for reference until after the discussion

**Comment by adamavenir** [comment]
I think it's perfectly reasonable to have an "edge" portion of the graph content that's for non-MTI codecs, but to make it clear that these are not the present standard.

This information is likely interesting to at least a subset of people who use this site as a reference.

**Pull request merged**
