### PR TITLE
Bowser supports dataChannels

### PR DESCRIPTION
**Pull request by pantaoran**
The field there should be green now.

### CODE REVIEW

**Comment by stefanalund** [comment]
Thanks @pantaoran!

**Comment by fippo** [comment]
@feross might be interested in this

**Comment by feross** [comment]
Nice - good to know!

**Comment by feross** [comment]
The App Store version doesn't seem to actually have Data Channel support. When will that be released?

**Comment by pantaoran** [comment]
Huh? I'm successfully establishing data channels with the app store version... what makes you say this?

**Comment by feross** [comment]
Is there a different prefix to use for the RTCPeerConnection? I'm detecting
no support.

**Comment by stefanalund** [comment]
@feross here's the JavaScript bridge used by Bowser: https://github.com/EricssonResearch/openwebrtc/blob/master/bridge/client/webrtc.js#L318

**Comment by pantaoran** [comment]
There is someone else who complained that they saw no support for data channels here: https://github.com/EricssonResearch/bowser/issues/27#issuecomment-143099346

But that doesn't happen to me, when I try with Bowser 0.5 on iPad Air 2 with iOS 8 it has support and the chat checkbox can be clicked.

**Pull request merged**
