### PR TITLE
update edge/ortc

### PR DESCRIPTION
**Pull request by fippo**
some updates. Need to check TURN support and WebAudio

### CODE REVIEW

**Comment by bear** [comment]
+1

**Comment by xdumaine** [comment]
:+1:

**Comment by jan-ivar** [comment]
🍺

**Comment by ShijunS** [comment]
@fippo, Edge supports TURN, doesn't allow WebAudio to access remote audio

**Comment by fippo** [comment]
@ShijunS thanks, updated accordingly.

The only thing I am pondering is the "solid interoperability" thing. If we bump everything else from yellow to green I would consider audio-only enough for yellow (it's just a video codec issue at that point). But that is a different PR.

**Pull request merged**
