### PR TITLE
Bowser

### PR DESCRIPTION
**Pull request by richardmitic**
Adding Bowser to the list of WebRTC capable browsers.

### CODE REVIEW

**Comment by fippo** [comment]
oh, bowser supports multiple audio/video streams on a single peerconnection?

**Comment by richardmitic** [comment]
@stefanalund, would you be able to confirm this?

**Comment by stefanalund** [comment]
@pererikb or @superdump may know.

**Comment by superdump** [comment]
I don't think we have tested it yet but it absolutely should. It should be quite easy to test the core functionality by adding extra audio/video media sessions in test_send_receive.c for example.

**Comment by superdump** [comment]
@pererikb has tested this with a video test source and a camera and that worked. When using two different cameras on OS X, there was a bug in the camera source component on just that platform but we'll get that fixed. So it looks like the answer is "yes, but as it is not so well-tested yet there may be a few bugs to fix."

**Pull request merged**
