### PR TITLE
can we now agree its ready

### PR DESCRIPTION
**Pull request by fippo**
to go to school at least. Besides nobody is updating this table anyway and there are more useful ways to nag people.

### CODE REVIEW

**Comment by xdumaine** [comment]
My only suggestion would be to link to various bug trackers, discuss-webrtc, webrtc.org, samples, and adapter.

**Comment by fippo** [comment]
I like that suggestion actually.

**Comment by silviapfeiffer** [comment]
It's not really about nagging, but more like a http://caniuse.com/ for WebRTC. Just my 2c worth - I would just change the messaging, not remove the table.

**Review by xdumaine — APPROVED** [review]

**Comment by fippo** [comment]
@silviapfeiffer  when I looked at the table i noted a couple of things which were outdated. Nobody is maintaining this table sadly :-/

**Comment by adamavenir** [comment]
👍

**Comment by silviapfeiffer** [comment]
@fippo since you've moved it to legacy, that's ok. An update every few months is actually sufficient. ;-)

**Comment by fippo** [comment]
merged. It is actually tempting to point out the lack of VP8 in Safari but....

**Pull request merged**
