### PR TITLE
is webrtc ready

### PR DESCRIPTION
**Pull request by fippo**
I think this page has done it's job.

### CODE REVIEW

**Comment by adamavenir** [comment]
I think there's still value in tracking state of various APIs. 

How about just an `<h1>Yes.</h1>` above the table?

**Comment by fippo** [comment]
the table is lacking detail. I don't think that is fixable.

**Comment by silviapfeiffer** [comment]
I don't follow - obviously not all browsers support WebRTC yet, so why would you think it's ready? What do we point people to alternatively to find out about implementation status? Is your problem that this is too hard to maintain?

**Comment by fippo** [comment]
that hasn't prevented adoption (e.g. by facebook messenger which is rumored to be 10% of global voip traffic). The purpose of this website has been pushing browser vendors to improve in certain areas. However, if you look at the last... four... chrome releases there is nothing here that changed. Despite massive improvements in chrome.

**Comment by silviapfeiffer** [comment]
Hmm... it was always a nice page to use to encourage other browsers and to explain progress across browsers to customers. For developers, we always have caniuse.com, I guess. It all depends on your definition of "ready", of course! Standard? Browsers? Operating Systems? Devices?

**Comment by fippo** [comment]
Given Facebook's usage of webrtc (see https://webrtchacks.com/facebook-webrtc/ -- writing that was actually the reason for this PR) I still think it is ready.

**Comment by silviapfeiffer** [comment]
Could we split the details if interoperability from the "is it ready yet" question? I can see how it's important to promote the idea that it's ready, but we should not imply that all work is done.

**Comment by lisamarienyc** [comment]
I agree with Silvia -- "is WebRTC ready to do X" may be a more helpful
question to answer.

// Lisa Larson-Kelley

**Pull request closed without merging**
