### PR TITLE
Add makefile and building-static-server

### PR DESCRIPTION
**Pull request by latentflip**
This standardises the project as per &yet build tooling work, and
ensures anyone can build stylus/get livereload benefits without
having to install external things.

index.html formatting has just changed slightly because of differing jade process.

### CODE REVIEW

**Comment by adamavenir** [comment]
When running `npm i`, it looks like there's some issue install make-better.

```
npm ERR! make-better@0.3.0 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the make-better@0.3.0 install script.
```

**Comment by latentflip** [comment]
Re-raised under nlf/git-validate#11

**Comment by latentflip** [comment]
This should now be fixed so you should be good to go @adambrault

**Comment by xdumaine** [comment]
I think maybe this should be closed since the jade file was removed?

**Comment by bear** [comment]
+1 - Makefile is no longer required as it's nothing but a static html site now

**Pull request closed without merging**
