### PR TITLE
Switch license to CC BY-SA 3.0 Unported

### PR DESCRIPTION
**Pull request by Calinou**
This switches to the free culture CC BY-SA 3.0 Unported license. [More information](http://freedomdefined.org/Licenses/NC).

### CODE REVIEW

**Comment by bear** [comment]
It's already showing as licensed CC BY-SA v3 Unported so I'm confused as to the change needed

_edit_ - thanks to fippo for showing me the bit I missed, reviewing the change now - thanks

**Comment by bear** [comment]
I'm going to leave this for a week to give folks a chance to raise any questions or objections and if none are given (or accepted) then I will merge.

thanks!

**Comment by xdumaine** [comment]
:+1:

**Comment by bear** [comment]
@Calinou looks like the PR has gone stale, can you update it and then i'll get it merged

**Comment by Calinou** [comment]
Redone here: https://github.com/webrtcftw/iswebrtcreadyyet.com/pull/67

**Pull request closed without merging**
